MRA_V2_LEEF_MAPPING = (
    # General
    ("entName", "lookoutEntName"),
    ("change_type", "lookoutChangeType"),
    ("created_time", "lookoutEventTime"),
    ("enterprise_guid", "lookoutEnterpriseGuid"),
    ("id", "lookoutId"),
    ("type", "lookoutType"),
    ("target.guid", "lookoutTargetId"),
    ("target.type", "targetType"),
    ("actor.guid", "lookoutActorId"),
    ("actor.type", "lookoutActorType"),
    # Audit Event
    ("audit.attribute_changes", "lookoutAttributeChanges"),
    ("audit.type", "lookoutEventType"),
    # Device Event
    ("device.guid", "lookoutDeviceGuid"),
    ("device.platform", "lookoutTargetPlatform"),
    ("device.profile_type", "deviceProfileType"),
    ("device.client.lookout_sdk_version", "lookoutClientSDKVersion"),
    ("device.client.ota_version", "lookoutClientOTAVersion"),
    (
        "device.client.package_name",
        "device.client.package_version",
        "lookoutClientPackageDetails",
        lambda name, version: f"{name}-{version}",
    ),
    ("device.hardware.manufacturer", "deviceManufacturer"),
    ("device.hardware.model", "deviceModel"),
    ("device.info.customer_device_id", "customerDeviceId"),
    ("device.info.device_group_guids", "lookoutDeviceGroupGuids"),
    ("device.info.email", "lookoutUser"),
    ("device.info.external_id", "lookoutTargetExternalId"),
    ("device.info.mdm_connector_id", "LookoutMdmConnectorId"),
    ("device.info.mdm_type", "mdmType"),
    ("device.info.previous_device_group_guids", "previousDeviceGroupGuids"),
    ("device.parent_status.activation_status", "parentActivationStatus"),
    ("device.parent_status.parent_device_guid", "parentDeviceGuid"),
    ("device.parent_status.protection_status", "parentProtectionStatus"),
    ("device.parent_status.security_status", "parentSecurityStatus"),
    ("device.software.latest_os_version", "latestOSVersion"),
    ("device.software.latest_security_patch_level", "latestSecurityPatch"),
    ("device.software.os_version", "lookoutOSVersion"),
    ("device.software.os_version_date", "OSVersionDate"),
    ("device.software.os_version_rsr", "OSVersionRSR"),
    ("device.software.sdk_version", "SDKVersion"),
    ("device.software.security_patch_level", "securityPatch"),
    ("device.status.activation_status", "lookoutActivationStatus"),
    ("device.status.checkin_time", "checkinTime"),
    ("device.status.protection_status", "lookoutProtectionStatus"),
    ("device.status.security_status", "lookoutSecurityStatus"),
    # Threat Event
    ("threat.guid", "lookoutThreatId"),
    ("threat.severity", "lookoutSeverity"),  # TODO: map this to 1-10 to match QRadar `sev` field
    ("threat.type", "lookoutEventType"),
    ("threat.classifications", "lookoutClassifications"),
    ("threat.assessments", "threatAssessments"),
    ("threat.details.dns_ip_addresses", "lookoutDnsIpAddresses"),
    ("threat.details.file_name", "lookoutAppFileName"),
    ("threat.details.latest_agent_config", "latestAgentConfig"),
    ("threat.details.latest_os_version", "latestOSVersion"),
    ("threat.details.mac_address", "lookoutMacAddress"),
    ("threat.details.minimum_os_version", "threatMinOSVersion"),
    ("threat.details.network_ssid", "lookoutSSID"),
    ("threat.details.os_version", "OSVersion"),  # shared with device.software.os_version
    (
        "threat.details.application_name",
        "threat.details.package_name",
        "lookoutAppProcessDetails",
        lambda app, pack: f"{app}, {pack}",
    ),
    ("threat.details.package_sha", "threatAppPackageSHA"),
    ("threat.details.path", "lookoutAppFilePath"),
    ("threat.details.proxy_address", "lookoutProxyAddress"),
    ("threat.details.proxy_port", "lookoutProxyPort"),
    ("threat.details.proxy_protocol", "lookoutProxyProtocol"),
    ("threat.details.reason", "threatReason"),
    ("threat.details.response", "threatResponse"),
    ("threat.details.trusted_signing_identity", "lookoutTrustedSigningIdentity"),
    ("threat.details.url", "lookoutUrl"),
    ("threat.details.user_response", "threatUserResponse"),
    ("threat.details.version_type", "threatVersionType"),
    ("threat.details.vpn_local_address", "lookoutVpnLocalAddress"),
    (
        "threat.details.vpn_present",
        "lookoutVpnPresent",
        lambda present: 1 if present else 0,
    ),
    ("threat.details.network.access_point_hostname", "accessPointHostname"),
    (
        "threat.details.network.connected",
        "networkConnected",
        lambda connected: 1 if connected else 0,
    ),
    ("threat.details.network.dns_ip_address", "dnsIpAddress"),
    ("threat.details.network.network_name", "networkName"),
    ("threat.details.network.network_type", "networkType"),
    ("threat.details.network.proxy_config", "proxyConfig"),
    ("threat.details.network.vpn_configuration", "vpnConfiguration"),
    ("threat.details.network.wifi_bssid", "wifiBSsid"),
)
